apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voiceguard-ingress
  namespace: voiceguard-system
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: "voiceguard-service"
spec:
  rules:
    - host: voiceguard.cybersecurity.aicte.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: voiceguard-service
                port:
                  number: 80
