apiVersion: v1
kind: Secret
metadata:
  name: voiceguard-secret
  namespace: voiceguard-system
type: Opaque
stringData:
  SECRET_KEY: "voiceguard_super_secret_jwt_key_2026_aicte_cybersecurity"
  DATABASE_URL: "sqlite:///./voiceguard.db"
